### PR TITLE
fix: trim only when necessary if trimming is off

### LINKED ISSUE #384: Only trim nodes if parent can't contain text nodes
When parsing html, in most cases we need to enable trim to prevent the `validateDOMNesting` errors

```ts
domToReact(html, {trim: true})
```

However this doesn't always work. There may be cases where a div contains a `&nbsp` character. During parsing, this gets trimmed out. 

```ts
const html = `
  <div>     Hello</div>
`;

function App() {
  return parse(html, { trim: true });
}
````
[CodeSandBox Demo](https://codesandbox.io/s/html-react-parser-205-forked-zvbmz)

Note, the whitespace before the `Hello` aren't spaces . They are `&nbsp`.

Would you be open to the idea of allowing users to provide a function for trim that would allow specifying a custom trimmer to handle these special spaces? It would look something like this

```ts
const customTrim = node => {
  const data = node.data;
  // some trimming logic
  return data;
}

return parse(html, { trim: customTrim });
```
I could even see it being extended to check if the node type allows spaces or not and trimming based on that although this can be done in the replacer function also as suggested in #205

```ts
const customTrim = node => {
  const {type, name, data} = node;
  if(type === 'tag' && ['div', 'p', ...etc].contains(name)) {
    return data
  }
  return data.trim()
}
```

I'm happy to create a PR if you're open to this idea

### PR DESCRIPTION
**Pull request by vidhu**
Fixes #384

## What is the motivation for this pull request?
Fixes an issue #384 where trimming can lead to inaccurate parsing when nodes have whitespace characters

## What is the current behavior?
 - if trim is off, whitespace characters trigger reacts validation errors
 - if trim is on, whitespaces are stripped from nodes that can contain white spaces which results in inaccurate parsing

## What is the new behavior?
Regardless of the trimming setting, if a text node appears in a node that can contain text nodes eg `<table>`, `<tr>`, it will be removed. If trimming is off, then whitespaces are preserved in nodes that can contain text nodes. 

## Checklist:

- [x] [Conventional Commits](https://www.conventionalcommits.org/)
- [x] Tests
- [x] Documentation
- [x] Types

Looking for approvals before I add to documentation!

### CODE REVIEW

File: lib/dom-to-react.js [hunk 1]
```diff
@@ -51,15 +52,23 @@ function domToReact(nodes, options) {
...
-      if (trim) {
-        data = node.data.trim();
-        if (data) {
-          result.push(node.data);
-        }
-      } else {
-        result.push(node.data);
+      isWhitespace = !node.data.trim().length;
+
+      if (isWhitespace && node.parent && !canTextBeChildOfNode(node.parent)) {
```
Comment (remarkablemark) [inline lib/dom-to-react.js:57]: Can we do the `node.parent` check in `canTextBeChildOfNode()`?

File: lib/dom-to-react.js [hunk 2]
```diff
@@ -51,15 +52,23 @@ function domToReact(nodes, options) {
...
+        // We have a whitespace node that can't be nested in it's parent
```
Comment (remarkablemark) [inline lib/dom-to-react.js:58]: Grammar: replace `it's` with `its`

File: lib/utilities.js [hunk 3]
```diff
@@ -96,9 +96,35 @@ function setStyleProp(style, props) {
...
+  'tbody',
+  'thead',
+  'tfoot',
+  'colgroup',
+  'table',
+  'head',
+  'html',
+  'frameset',
+  '#document'
+]);
```
Comment (remarkablemark) [inline lib/utilities.js:112]: How often would we have to maintain this list?

File: lib/utilities.js [hunk 4]
```diff
@@ -96,9 +96,35 @@ function setStyleProp(style, props) {
...
+
+/**
+ * Returns True if the the given node can contain text nodes
```
Comment (remarkablemark) [inline lib/utilities.js:115]: Nit: replace line with:

```
Checks if the the node can contain text nodes.
```

File: lib/utilities.js [hunk 5]
```diff
@@ -96,9 +96,35 @@ function setStyleProp(style, props) {
...
+ * @param {DomElement} node
```
Comment (remarkablemark) [inline lib/utilities.js:116]: Nit: add newline above

File: lib/utilities.js [hunk 6]
```diff
@@ -96,9 +96,35 @@ function setStyleProp(style, props) {
...
+ * @returns {boolean}
+ */
+function canTextBeChildOfNode(node) {
+  return !elementsWithNoTextChildren.has(node.name);
```
Comment (remarkablemark) [inline lib/utilities.js:120]: Can you check node validity here?

```js
return node && node.parent && !elementsWithNoTextChildren.has(node.name);
```

File: test/index.test.js [hunk 7]
```diff
@@ -138,13 +138,16 @@ describe('htmlparser2 option', () => {
 });
 
 describe('trim option', () => {
-  it('preserves whitespace text nodes when disabled (default)', () => {
+  it('preserves whitespace text nodes when disabled if valid in parent (default)', () => {
     const html = `<table>
   <tbody>
+    <tr><td>\n</td>\t</tr>\r
```
Comment (remarkablemark) [inline test/index.test.js:144]: Can you add a test with text and `&nbsp;`?

File: test/index.test.js [hunk 8]
```diff
@@ -138,13 +138,16 @@ describe('htmlparser2 option', () => {
...
   </tbody>
 </table>`;
     const reactElement = parse(html);
-    expect(render(reactElement)).toBe(html);
+    expect(render(reactElement)).toBe(
+      '<table><tbody><tr><td>\n</td></tr></tbody></table>'
+    );
```
Comment (remarkablemark) [inline test/index.test.js:150]: Can you also add a snapshot test?

```js
expect(reactElement).toMatchInlineSnapshot();
```

I'm curious to see how the snapshot will format the output

File: test/utilities.test.js [hunk 9]
```diff
@@ -125,3 +127,22 @@ describe('setStyleProp', () => {
     expect(props).toEqual({ style: {} });
   });
 });
+
+describe('canTextBeChildOfNode', () => {
+  it.each(Array.from(elementsWithNoTextChildren))(
+    'returns false since text node can not be child of %s',
```
Comment (remarkablemark) [inline test/utilities.test.js:133]: Grammar: replace `can not` with `cannot`

File: lib/dom-to-react.js [hunk 10]
```diff
@@ -51,15 +52,23 @@ function domToReact(nodes, options) {
...
+        continue;
       }
+
+      if (trim && isWhitespace) {
+        // Trim is enabled and we have a whitespace node
+        // so skip it
+        continue;
+      }
+
+      // We have a text node thats not whitespace and it can be nested
```
Comment (remarkablemark) [inline lib/dom-to-react.js:69]: Grammar: replace `thats` with `that's`

**Review by remarkablemark — CHANGES_REQUESTED** [review]
Left comments

File: lib/utilities.js (hunk 6 above)
Comment (vidhu) [reply lib/utilities.js:121]: I don't really know if that makes sense.

This function only checks if the passed in node can contain a text node or not. eg
`<table>` -> No, it can't contain a text
`<div>` -> Yes, it can't contain a text

If I do the check you've suggested, then that changes the meaning of the function. i.e "is the passed in node a valid child of its parent"

File: lib/dom-to-react.js (hunk 1 above)
Comment (vidhu) [reply lib/dom-to-react.js:57]: I responded to another comment you had related to this. Let me know what you think.

I could change the implementation to accept an `undefined` node but that wouldn't be really correct since `canTextBeChildOfNode(undefined)` would have to return `true`. This is incorrect because you can't actually have a text node as a child of something that undefined.

**Comment by vidhu** [comment]
> Left comments

Thank you. I've resolved the ones I've fixed and replied to your other comments

File: lib/utilities.js (hunk 3 above)
Comment (remarkablemark) [reply lib/utilities.js:112]: Great!

File: lib/dom-to-react.js (hunk 1 above)
Comment (remarkablemark) [reply lib/dom-to-react.js:57]: Ggoing to resolve this conversation and keep discussion in https://github.com/remarkablemark/html-react-parser/pull/394#discussion_r769201694

File: lib/utilities.js (hunk 6 above)
Comment (remarkablemark) [reply lib/utilities.js:121]: Makes sense, let's keep it as-is

File: lib/utilities.js [hunk 11]
```diff
@@ -96,9 +96,36 @@ function setStyleProp(style, props) {
...
+  'tr',
+  'tbody',
+  'thead',
+  'tfoot',
+  'colgroup',
+  'table',
+  'head',
+  'html',
+  'frameset',
+  '#document'
```
Comment (remarkablemark) [inline lib/utilities.js:111]: Question: which element would this be?

**Review by remarkablemark — APPROVED** [review]
Looks good! Will you be updating docs @vidhu?

**Comment by vidhu** [comment]
> Looks good! Will you be updating docs @vidhu?

Yes! Just pushed out a commit to update the docs.

File: lib/utilities.js (hunk 11 above)
Comment (vidhu) [reply lib/utilities.js]: Good question, I'm not sure myself. I just copied it over from react's source. I've removed it since I don't think it is something that part of an HTML structure. [MSDN states](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName) that it's an interface to an already loaded document in a browser so it doesn't seem to apply to us.

File: README.md [hunk 12]
```diff
@@ -351,16 +351,16 @@ By default, whitespace is preserved:
 parse('<br>\n'); // [React.createElement('br'), '\n']
 ```
 
-To remove whitespace, enable the `trim` option:
+However, whitespace that are invalid under certain nodes like `<table>` will be stripped out.
```
Comment (remarkablemark) [inline README.md:354]: Nit: can you update to:

```suggestion
But certain elements like `<table>` will strip out invalid whitespace:
```

File: README.md [hunk 13]
```diff
@@ -351,16 +351,16 @@ By default, whitespace is preserved:
...
 
 ```js
-parse('<br>\n', { trim: true }); // React.createElement('br')
+parse('<table>\n</table>'); // [React.createElement('table')]
```
Comment (remarkablemark) [inline README.md:357]: Should this be?

```suggestion
parse('<table>\n</table>'); // React.createElement('table')
```

File: README.md [hunk 14]
```diff
@@ -427,10 +427,6 @@ parse('<div /><div />'); // returns single element instead of array of elements
 
 See [#158](https://github.com/remarkablemark/html-react-parser/issues/158).
 
-### Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of table
```
Comment (remarkablemark) [inline README.md:430]: Can you also remove in the README's table of contents?

**Review by remarkablemark — CHANGES_REQUESTED** [review]
Left comments

**Comment by vidhu** [comment]
Thank you @remarkablemark I've addressed your requested changes

**Review by remarkablemark — APPROVED** [review]
Thanks, looks good @vidhu!

**Comment by remarkablemark** [comment]
Released in https://github.com/remarkablemark/html-react-parser/pull/395#issuecomment-997154880

**Comment by vidhu** [comment]
Thank you! Pleasure working with you :)

**Comment by remarkablemark** [comment]
Same here! @vidhu If you're ever interested in being a maintainer for `html-react-parser`, I'd be happy to extend the offer.

**Comment by vidhu** [comment]
Thank you. I would be interested in that. Do you use any instant messaging platform like discord?

**Comment by remarkablemark** [comment]
Yes! We have a [Discord](https://discord.gg/njExwXdrRJ) server, feel free to DM me once you join
