### PR TITLE
fix: use JSX.Element for type definitions

### LINKED ISSUE #145: dom-to-react.d.ts should reference JSX.Element instead of React.ReactElement
Although this library can be used with Preact/Inferno/etc, the typings make it hard to do so as they rely explicitly on React types. Instead, JSX.Element should be used as it's more compatible across libraries.

I'd PR this, but I'm uncertain as to how dependent the library is on React internals.

### PR DESCRIPTION
**Pull request by yunyu**
## What is the motivation for this pull request?

This makes the library usable for non-React JSX implementations in TypeScript. JSX.Element is defined as React.ReactElement for the 'react' package, and is [overridden by other JSX implementations](https://devblogs.microsoft.com/typescript/announcing-typescript-2-8-rc/). Fixes #145.

## What is the current behavior?

Currently, trying to use html-react-parser with Preact in TS will result in a bunch of type errors.

## What is the new behavior?

* React.ReactElement is replaced with JSX.Element, which aliases to React.ReactElement for the current tests
* The HTMLReactParser return value matches the domToReact return value, since the former returns the output of the latter

## Checklist:

- [X] Tests

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -9,24 +8,21 @@ export interface HTMLReactParserOptions {
   // TODO: Replace `object` by type for objects like `{ type: 'h1', props: { children: 'Heading' } }`
   replace?: (
     domNode: DomElement
-  ) => React.ReactElement | object | void | undefined | null | false;
+  ) => JSX.Element | object | void | undefined | null | false;
   library?: object;
 }
 
 /**
  * Converts HTML string to React elements.
```
Comment (remarkablemark) [inline index.d.ts]: Nit: to make it consistent with the line below:
```
Converts HTML string to JSX element(s).
```

File: index.d.ts [hunk 2]
```diff
@@ -9,24 +8,21 @@ export interface HTMLReactParserOptions {
...
  *
- * @param  html    - The HTML string to parse to React.
+ * @param  html    - The HTML string to parse to JSX.
```
Comment (remarkablemark) [inline index.d.ts]: Nit: do you mind updating to:
```
The HTML string to parse to JSX element(s).
```

File: lib/dom-to-react.d.ts [hunk 3]
```diff
@@ -1,17 +1,16 @@
...
 
 /**
  * Converts DOM nodes to React elements.
  *
- * @param nodes - A list of formatted DomNodes to convert to React.
- * @param options - Options to use when converting to react.
- * @returns ReactElement or and array of ReactElements.
+ * @param nodes - A list of formatted DomNodes to convert to JSX.
+ * @param options - Options to use when converting to JSX.
+ * @returns JSX.Element or an array of JSX.Elements.
```
Comment (remarkablemark) [inline lib/dom-to-react.d.ts]: Can we update this to:
```
@return Single or array of JSX elements.
```

File: lib/dom-to-react.d.ts [hunk 4]
```diff
@@ -1,17 +1,16 @@
...
 import { HTMLReactParserOptions } from '..';
 import { DomElement } from 'domhandler';
 
 /**
  * Converts DOM nodes to React elements.
  *
- * @param nodes - A list of formatted DomNodes to convert to React.
- * @param options - Options to use when converting to react.
- * @returns ReactElement or and array of ReactElements.
+ * @param nodes - A list of formatted DomNodes to convert to JSX.
```
Comment (remarkablemark) [inline lib/dom-to-react.d.ts]: Minor: do you mind updating:
```
An array of DOM nodes to convert to JSX.
```

**Comment by yunyu** [comment]
@remarkablemark I've made the requested changes

**Comment by remarkablemark** [comment]
I'll make a release later tonight
